### ISSUE TITLE
Testing a package that is Symlinked to packages

### ISSUE THREAD

**Issue by asfaltboy** [SublimeText/UnitTesting#104]
I normally put all code I'm working on under a `~/dev` dir. My use case mat not be the standard, but it normally works for me just fine.

Trouble is that with UnitTesting, the `UnitTestingMixin.current_package_name` property always returns `None` so I always need to run `UnitTesting` command and specify the package. Moreover, the command runs for all tests and doesn't let me run for a single test file as I always get the "Cannot determine package name." error dialog.

I can see this happens due to the condition `relative_to_spp` always failing for my symlinked path:

https://github.com/SublimeText/UnitTesting/blob/d495d044750d0e4a0b5e6bdb713d908b3d9eeeaf/unittesting/mixin.py#L20-L27

Is there a reason we're using `os.path.realpath`? Why not just use `path` as is? I could only trace the usage of `realpath` to the original commit that implemented looking up the project name here:
84992661703ee99a9e439c5ede214168f673aecb

An alternative to this, is to allow users set the package name, e.g in project settings.

**Comment by randy3k** [comment]
Are you running on the master branch? I believe we have fixed it at https://github.com/SublimeText/UnitTesting/commit/bccbc6e304dcb616d40f4d185fafe8ed16c055b6

**Comment by asfaltboy** [comment]
Yes! Thanks that worked.

Not sure why I had a relative path in my `project-settings` ... but changing it to the package path under `.../Sublime Text 3/Packages` worked well.

Unrelated to this, I'm getting `ImportError: No module named 'unittesting.helpers'` when running GitSavvy test case with latest UnitTesting installed... Could be that this commit is to blame: baf4428700d83c1a7b77194b9cfc33f33556a4dc

We're using it here:

https://github.com/divmain/GitSavvy/blob/1196f7819ebbc2b8de71222481c23ea58b4553ec/tests/test_git/common.py#L4

**Comment by asfaltboy** [comment]
Thanks, and sorry for delay, only had a chance to check now. I managed to resolve this by completely removing UnitTesting package (via package control), restarting sublime and re-installing it (via package control), now all is well!
