### ISSUE TITLE
AppVeyor System.Version error

### ISSUE THREAD

**Issue by ehuss** [SublimeText/UnitTesting#118]
Just tried to do an AppVeyor build, and got the following error:

```
Downloading appveyor.ps1 (5,609 bytes)...100%
.\appveyor.ps1 "bootstrap" -verbose
VERBOSE: copy the package to sublime text Packages directory
Cannot convert value "st2-0.10.6" to type "System.Version". Error: "Input string was not in a correct format."
```

Looks like there is an odd tag on the https://github.com/randy3k/UnitTesting repo.  Am I doing something wrong?

**Comment by jgirardet** [comment]
same thing https://ci.appveyor.com/project/jgirardet/sublack/build/1.0.35

**Comment by niosus** [comment]
Same happens here: https://ci.appveyor.com/project/jgirardet/sublack/build/1.0.35

**Comment by gerardroche** [comment]
I'm getting some of these error too:

https://ci.appveyor.com/project/gerardroche/sublime-phpunit/branch/master

https://ci.appveyor.com/project/gerardroche/sublime-php-grammar/branch/master

**Comment by guillermooo** [comment]
@randy3k I'm having this issue too. It seems to be due to a tag `st2-0.10.6`. Maybe removing it would sove the issue.

Details:

```
2018-07-04T04:51:54.9840436Z ##[error]% : Cannot convert value "st2-0.10.6" to type "System.Version". Error: "Input string was not in a correct format."
At D:\a\1\s\appveyor.ps1:40 char:61
+ ...           | where-object {$_ -notmatch "\^"} |%{[System.Version]$_} `
+                                                   ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation,Microsoft.PowerShell.Commands.ForEachObjectCommand
 

2018-07-04T04:51:56.3456108Z ##[error]Process completed with exit code 1 and had 1 error(s) written to the error stream.
```

**Comment by randy3k** [comment]
Oh, I didn’t receive any notifications. I must have disabled it...

The prefix is needed for Package Control on Sublime Text 2. I guess we need to fix the script by filtering the prefix.
