### ISSUE TITLE
"Test Current Package" doesn't work with async

### ISSUE THREAD

**Issue by ehuss** [SublimeText/UnitTesting#119]
The "Test Current Package" command doesn't seem to work with `async` projects.  It blocks the main thread preventing some things from working.

## Example
Create a project with `"async": true` in `unittesting.json`.  Add the following test:

```python
import sublime
from unittest import TestCase
import threading
import time

class TestAsync(TestCase):

    def test_async(self):
        window = sublime.active_window()
        view = window.open_file('somefile')

        def wait_for_loaded():
            for n in range(100):
                if view.is_loading():
                    time.sleep(0.01)
                else:
                    break
            else:
                print('view never loaded')

        t = threading.Thread(target=wait_for_loaded)
        t.start()
        t.join()
```

This will **hang** sublime indefinitely on the call to `view.is_loading()` (must kill `plugin_host`).

## Possible Fix
I tracked this problem back to a change in d9f600080bcdc179927545f9701b3e81bd2c23bb.  The offending line is: https://github.com/SublimeText/UnitTesting/blob/ff46c925e44f56c898e9f9a8ff4a8521dbf990ac/unittesting/test_current.py#L22

Calling `set_timeout` here causes it to run on the main thread, ignoring the `async` parameter.  (Previously this code used to run *before* the async thread is created.)  I'm uncertain why it is calling `set_timeout` in the first place.  Just calling `unit_testing()` directly seems to work.  Alternatively, it could check the `async` setting and use `set_timeout_async()` instead?

**Comment by randy3k** [comment]
@ehuss 
Sorry for the late reply. For some reasons, I have disabled notifications of this repo. I'll look at it a.s.a.p.
