### ISSUE TITLE
Add syntax compatibility test

### ISSUE THREAD

**Issue by ehuss** [SublimeText/UnitTesting#129]
I think it would be nice to have an automated test to ensure that a `sublime-syntax` does not use the Oniguruma engine.  It looks like it would involve calling `sublime_api.incompatible_syntax_patterns(syntax_path)`.  Perhaps it would be exposed as a separate command like `run_tests.py --syntax-compatibility`.  What do you think about this idea?

**Comment by randy3k** [comment]
It sounds cool. I will be glad if someone figured out the sublime api to do it.
