### ISSUE TITLE
The Framework can be used in Oracle package unitest?

### ISSUE THREAD

**Issue by suexiukjung** [SublimeText/UnitTesting#131]
In the example project ,I see test*.py files (python files) in folder "tests". If I can use this framework for Oracle package unitest (test*.pck or test*.pkg files)?  Thanks~

**Comment by randy3k** [comment]
I do not understand entirely what you meant. This package is a testing framework for Sublime Text packages, not for running tests for any languages.

**Comment by suexiukjung** [comment]
ok, I see ! thanks for your quickly reply
