### ISSUE TITLE
[Feature] have log on test report

### ISSUE THREAD

**Issue by jgirardet** [SublimeText/UnitTesting#135]
Hi,
Log and print commands are displayed in sublimetext console.
Locally it's easy to access them but we can't access them in CI which make things harder to debug since we only have access to test result.
For example I'm suffering with debugging code running some subprocess.Popen but I'can't acess to their logs.

Jimmy

**Comment by randy3k** [comment]
You could use the `capture_cobsole` setting in `unittesting.json`

**Comment by jgirardet** [comment]
nothing changed with capture_console to true.

I tried also to access stdout but _LogWriter does not permit to read anything

**Comment by jgirardet** [comment]
maybe I miss understand.
What should I see with capture_console ? plugins logs ? tests logs ?

**Comment by randy3k** [comment]
It can be specified in [unittesting.json](https://github.com/SublimeText/UnitTesting/blob/master/unittesting.json) of your own package.

**Comment by jgirardet** [comment]
ok thank you  I can see my tests logs, but It doesn't show my code log.

**Comment by randy3k** [comment]
how did you log your code?

**Comment by jgirardet** [comment]
```
LOG = logging.getLogger(PACKAGE_NAME)
LOG.propagate = False
debug_formatter = logging.Formatter(
            "[{}:%(filename)s](%(levelname)s) %(message)s".format(PACKAGE_NAME)
        )
dh = logging.StreamHandler()
dh.setLevel(logging.DEBUG)
dh.setFormatter(debug_formatter)
LOG.addHandler(dh)
```

and I use `LOG.debug('my message')

**Comment by randy3k** [comment]
I see. It is because you are using a custom logger. Try to use the root logger instead.

**Comment by jgirardet** [comment]
indeed thanks
the `propagate = False` was the matter. Thanks !!
