### ISSUE TITLE
Build passing on Mac OS but falling for Linux with: Unit Testing pc_helper(), missing dependencies: {'coverage'}

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/UnitTesting#137]
Here you can see everything passing for the others, including Sublime Text on Mac OS:
1. https://travis-ci.org/evandrocoan/DebugTools/builds/440899598
1. ![image](https://user-images.githubusercontent.com/5332158/46900939-e6e98700-ce80-11e8-8f7d-0a1b1e01a7ce.png)

I had added `echo "first6 ls"; ls "/home/travis/.config/sublime-text-3/Packages"` on .travis.yml, and we can see the `coverage` dependency there:
```
ConcurrentLogHandler
coverage
DebugTools
DiffMatchPatch
PortalockerFiles
python-pywin32
UnitTesting
User
```

I manage to fix it by editing `pc_help.py`:
1. https://github.com/evandroforks/UnitTesting/commit/fde9b65eb95577cb99f6a3e39cbd8dc212e7e696
1. 
   ```python
   if len(missing_dependencies) == 0:
   # -->
   if len(missing_dependencies) == 0 or len(missing_dependencies) == 1 and 'coverage' in missing_dependencies:
   ```
Now the tests are passing:
1. ![image](https://user-images.githubusercontent.com/5332158/46901095-8ad43200-ce83-11e8-99be-2ed2cb076f10.png)
1. https://travis-ci.org/evandrocoan/DebugTools/builds/440905484

**Comment by randy3k** [comment]
It seems to a dirty fix. I would rather check the source if the error: why coverage was not installed or detected?

**Comment by randy3k** [comment]
`coverage` is removed in that line because it would soon be installed by Package Control

**Comment by evandrocoan** [comment]
I see AppVeyor also do that, but there are no problems over there. Somehow Package Control cannot install the missing dependency on Travis, while it can install on AppVeyour.

If UnitTesting package could capture the whole Sublime Text console, we could know why Package Control is failing in install the missing dependency on Travis. I also think that capturing the whole console would help most users to figure out errors on the remote machine.

**Comment by deathaxe** [comment]
Required libraries (former dependencies) are now resolved automatically via Package Control when running `setup` action. The mechanism is identical to how it would work locally.
