### ISSUE TITLE
Tests fail at downloading sublime text on travis

### ISSUE THREAD

**Issue by niosus** [SublimeText/UnitTesting#162]
As of recently, my tests fail at travis ci. See an example log here: https://travis-ci.org/niosus/EasyClangComplete/jobs/528523543 

The reported error is:
```
The command "sh travis.sh bootstrap" failed and exited with 1 during .
```

Do you have an idea why this could be happening?

Please tell me if you want to have a minimal example of this.

**Comment by randy3k** [comment]
Could it be a one-time event? I cannot reproduce it with one of my repo: https://travis-ci.org/randy3k/AlignTab/jobs/508159797

**Comment by niosus** [comment]
This is really strange. It works for you but not for me. I have just restarted the build just to see the same error. And the funny thing is that it seems that the command does everything it needs to do just returns the wrong exit status. :thinking:

**Comment by niosus** [comment]
It might be that this is what actually fails:
```bash
    - if [ "$PCINSTALL" == true ]; then sh travis.sh install_package_control; fi
```

**Comment by randy3k** [comment]
Might be around here? https://github.com/SublimeText/UnitTesting/blob/master/sbin/install_sublime_text.sh#L94

**Comment by randy3k** [comment]
I spotted is that the Travis containers which we are using are different. My one is python 3.3 and yours is the default python container 3.6. Travis updated their default python container two weeks ago, may be there is a missing library that ST needs in the new container.

**Comment by niosus** [comment]
I removed the line outlined in https://github.com/SublimeText/UnitTesting/issues/162#issuecomment-489613379 and it passes the line at least. So there seems to be the error installing package control.

**Comment by randy3k** [comment]
But the log said
```
The command "sh travis.sh bootstrap" failed and exited with 1 during .
```

So it seems the problem is the first line.

**Comment by niosus** [comment]
That is true. I tried to play around this a bit, but still don't get what exactly the issue is. If I remove the package control line the build passes until the point when it needs the presence of other packages installed through package control. I will keep looking in the coming days I guess.

**Comment by niosus** [comment]
I have narrowed it down to https://github.com/SublimeText/UnitTesting/blob/02b8873f068569c4fb4d3494e238136ee63a6006/sbin/install_sublime_text.sh#L96

I don't understand what happens her ethough and why the process cannot be killed. It probably means that it was not started, but if I add `|| true` to the end of line, I get errors related to MIR (weird?). If you have any ideas, just throw them in. :) At this point, I guess I have to sleep on this...

**Comment by niosus** [comment]
Also, the difference between our builds is that I got transferred to xenial while the ones you have shown me are still on trusty. This might explain the display-related code misbehaving.

**Comment by niosus** [comment]
Sorry for spamming. I've been able to complete the build in two ways:
- setting the linux build to `trusty` works out of the box with the same config as before, but trusty's time is running out.
- setting the linux build to `xenial`, which is now the default build on travis requires setting headless sublime in a different way. Instead of manually setting up headless sublime we have to use the built-in method now: 
```yaml
services:
- xvfb
```

**Comment by randy3k** [comment]
Great. Thanks for the investigation.
