### ISSUE TITLE
sh: 0: Can't open /etc/init.d/xvfb and curl: (22) The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/UnitTesting#163]
Travis is trying to be very funny lately.

First using a build matrix for Python 3.3 is:
1. With `python: 3.3`
   * curl: (22) The requested URL returned error: 404 Not Found
   * https://travis-ci.org/evandrocoan/debugtools/jobs/567462750

Then, I tried using Python 3.4, and now it says it cannot open `xvfb`
1. With `python: 3.4`
   * sh: 0: Can't open /etc/init.d/xvfb
   * https://travis-ci.org/evandrocoan/debugtools/jobs/567464482

Any ideas how I could fix this?

**Comment by randy3k** [comment]
are there still issues?

**Comment by evandrocoan** [comment]
Yes. I restarted both builds above. The python 3.3 link above still 404 not found:
1. https://travis-ci.org/evandrocoan/debugtools/jobs/567462750

And the python 3.4 still saying `sh: 0: Can't open /etc/init.d/xvfb`.
1. https://travis-ci.org/evandrocoan/debugtools/jobs/567464482

This is my part of the xvfb on my `.travis`
1. https://github.com/evandrocoan/debugtools/blob/a54da83a35f406179f105bf350294cf693b41edd/.travis.yml#L79-L82
   ```
       # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
       - if [ -z "$TOXENV" ] && [ "$TRAVIS_OS_NAME" == "linux"  ]; then
               export DISPLAY=:99.0;
               sh -e /etc/init.d/xvfb start;
         fi
   ```

**Comment by ehuss** [comment]
I'm seeing the same thing:

```
$ if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

sh: 0: Can't open /etc/init.d/xvfb

The command "if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi" failed and exited with 127 during .
```

It looks like Travis switched my default image from Trusty to Xenial a few days ago, which requires [a new way for using xvfb](https://benlimmer.com/2019/01/14/travis-ci-xvfb/) (see [docs](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui)).  I just added this to my yaml file:

```yaml
services:
  - xvfb
```

And removed manually starting xvfb. It looks like Travis takes care of setting `DISPLAY`, too.

**Comment by gwenzek** [comment]
I've the same errors. For python 3.3 I don't think we can do much, since it's not supported by Travis anymore: https://docs.travis-ci.com/user/languages/python/#specifying-python-versions

Here is how I modified my config to make it work again:
https://github.com/gwenzek/SublimeSetWindowTitle/commit/665bf6efa6b4a9414f3aff4bcb44b18ecfe33ee4

**Comment by randy3k** [comment]
anyone mind pushing a working .travis?

**Comment by gwenzek** [comment]
https://github.com/gwenzek/SublimeSetWindowTitle/blob/665bf6efa6b4a9414f3aff4bcb44b18ecfe33ee4/.travis.yml is working

**Comment by randy3k** [comment]
Fixed on master
