### ISSUE TITLE
GitHub Action failing on Linux

### ISSUE THREAD

**Issue by pykong** [SublimeText/UnitTesting#171]
Thanks for putting up UnitTesting fur Sublime!
Without it, much more headache is pre-programmed!

I could not get the Linux part of the GitHub Action run green, while Windows and Mac run just fine.
It seems `linux-libc-dev` can not be fetched.

Could you have a look at it?

**Error message:**
```sh
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.15.0-72.81_amd64.deb  404  Not Found [IP: 91.189.88.162 80]
```

**Have a look at the logs here:**
https://github.com/pykong/Helium/pull/84/checks?check_run_id=448151121

**Comment by randy3k** [comment]
It seems a random error from the ubuntu repos. Perhaps, just try again in a few days.

**Comment by pykong** [comment]
The issue is not due to flakiness. Linus workflows **never** succeed for me:

See for example my latest run:
https://github.com/pykong/Helium/pull/93/checks?check_run_id=475773680#step:7:1

**Comment by randy3k** [comment]
run `apt-get update` first?
