### ISSUE TITLE
Publish GitHub Action

### ISSUE THREAD

**Issue by pykong** [SublimeText/UnitTesting#172]
It would be great if the GitHub Action in this repo would be published.
The current `README.md` advises:
```
To enable GitHub Actions, copy the file build.yml to your repository.
```

It would be much better if we could simply put a reference in our workflow files, like so:
```yaml
- name: UnitTesting for Sublime Text 3
  uses: SublimeText/GitHub-Action-UnitTestingt@0.5.0
```

Example of a package allowing such reference:
https://github.com/cclauss/GitHub-Action-for-pytest

**Comment by randy3k** [comment]
That requires using github action toolkit to write a javascript based action which I don't have much experiences.

**Comment by pykong** [comment]
@randy3k Thanks for your response. Let me check on that.

**Comment by pykong** [comment]
@randy3k I could not get it to work either. Maybe there will be simpler ways for reusing GitHub Actions in the future as the platform matures.

Still, I would see this of tremendous value to plugin developers. 
Hence, I'll suggest leaving this issue open as a feature request.

**Comment by randy3k** [comment]
I kinda know what it works, but it requires writing JS/TS which I don't have many experiences and I don't have time to learn new things now.

**Comment by deathaxe** [comment]
Github Actions are available via

```
    ...
    steps:
      - uses: actions/checkout@v4
      - uses: SublimeText/UnitTesting/actions/setup@v1
      - uses: SublimeText/UnitTesting/actions/run-tests@v1
    ...
```
