### ISSUE TITLE
GitHub Action for Sublime Text 4

### ISSUE THREAD

**Issue by pykong** [SublimeText/UnitTesting#174]
It would be great to have a workflow for Sublime Text 4 as well.
Even if ST4 is not released yet, this would greatly help early-adopting plugin developers.

**Comment by randy3k** [comment]
There are two issues needed to be solved. St4 requires a key, 2 package control does not support st4 at this moment.

**Comment by pykong** [comment]
OK. Thanks for the update.

**Comment by yeraydiazdiaz** [comment]
I believe ST4 is now supported as described in the README:

> Sublime Text 4 is now supported. Test coverage on Python 3.8 packages is still not working until Package Control supports Python 3.8.

I think Package Control already support 3.8 as well, so maybe the README is outdated?

In any case we may want to close this issue.

**Comment by randy3k** [comment]
The latest version of Package Control still doesn't support Python 3.8 packages as far as I can tell.

**Comment by yeraydiazdiaz** [comment]
I don't have a ton of experience in the ecosystem but my package https://packagecontrol.io/packages/REST%20Client is 3.8 only and seems to work fine?

**Comment by randy3k** [comment]
It works because your package doesn't have any dependencies. Your package will probably fail if it specifies any dependencies.

**Comment by yeraydiazdiaz** [comment]
I see, thank you for clarifying. 👍🏻

**Comment by deathaxe** [comment]
ST4 is fully supported by 1.6.0+
