### ISSUE TITLE
Workflow failing `Can't open sbin/github.sh`

### ISSUE THREAD

**Issue by pykong** [SublimeText/UnitTesting#175]
I have copied the content of the example [build.yml](https://github.com/SublimeText/UnitTesting/blob/master/.github/workflows/build.yml) into a new file called `test.yml` and adapted events to only run on `push`.
See: [test.yml](https://github.com/pykong/Helium/blob/master/.github/workflows/test.yml)

The workflow is always failing on every platform - consistently, always. It is not due to flakiness.
The log reads: `sbin/github.sh`

See log:
https://github.com/pykong/Helium/runs/477953535#step:5:11

**Comment by randy3k** [comment]
https://github.com/SublimeText/UnitTesting/blob/master/.github/workflows/build.yml#L1

**Comment by pykong** [comment]
@randy3k Thanks for your update.
However, tests succeed with neither:
https://github.com/SublimeText/UnitTesting/blob/master/.github/workflows/build.yml#L1
nor:
https://github.com/randy3k/UnitTesting-example/blob/master/.github/workflows/build.yml

See output:
https://github.com/pykong/Helium/runs/478137314

**Comment by randy3k** [comment]
It seems that your plugin requires `typing` on Sublime Text 3.

```
ImportError: No module named 'typing'
```

**Comment by randy3k** [comment]
By the way, I am not sure if you really want to specify python 3.8. Package control doesn't download dependencies for python 3.8 (at the moment of writing).

**Comment by pykong** [comment]
> It seems that your plugin requires `typing` on Sublime Text 3.
> 
> ```
> ImportError: No module named 'typing'
> ```
I am not sure where you found that log entry, but thanks it is working now.

> By the way, I am not sure if you really want to specify python 3.8. Package control doesn't download dependencies for python 3.8 (at the moment of writing).

Yes, the specified python version is not ideal. Unfortunately, GitHub Actions do not support python 3.3.

**Comment by randy3k** [comment]
I cloned your package locally. Actually I have been following this project for a long time and it’s good to see that you are picking it up.

**Comment by pykong** [comment]
Ah. Great. I thought I was not able to read a log.

Yeah, indeed I saw your contributions to that package.
I like to give it some overhaul and especially better usability.

It is the only option when you want to do Jupyter on Sublime.
Therefore I believe it is an important landmark for the whole of Sublime's plugin ecosystem.
