### ISSUE TITLE
How to run syntax tests with GitHub Actions?

### ISSUE THREAD

**Issue by jwortmann** [SublimeText/UnitTesting#177]
I try to set up running syntax tests for a package I use (it is not on Package Control) and I think I have configured the GitHub Actions [workflow file](https://github.com/jwortmann/ini-syntax/blob/master/.github/workflows/syntax_test.yml) correctly. However, the tests fail because it seems like the syntax doesn't get applied (`[...] does not match scope [text.plain]` for all tests) - [see output here](https://github.com/jwortmann/ini-syntax/runs/493786746#step:6:32). The corresponding file extension is listed in the syntax definition file and I've even added a .sublime-settings file with those extensions because I found such a file in the linked [Assembly 6809 syntax repository](https://github.com/dougmasten/sublime-assembly-6809) (that one uses Travis though).

After the failed syntax tests, there is also a line `Packages/ini-syntax/.github/workflows/syntax_test.yml:1: unable to find SYNTAX TEST marker`, but I'm not sure what that means.

I'm new to GitHub Actions and CI in general. Any help would be appreciated!

**Comment by randy3k** [comment]
It is because your repo is called `ini-syntax` instead of `INI Syntax` as specified in https://github.com/jwortmann/ini-syntax/blob/master/syntax_test_ini.ini#L1

A fix would be to add an environmental variable `PACKAGE="INI Syntax"`.

**Comment by jwortmann** [comment]
Oh right, I forgot that I used that name for the package locally. Adding the environment variable solved the problem and all syntax tests are passing now, but I still get that additional error `Packages/INI Syntax/.github/workflows/syntax_test.yml:1: unable to find SYNTAX TEST marker`. Do you know how to resolve this? Thanks for your quick help!

**Comment by randy3k** [comment]
UnitTesting misclassied that `syntax_test.yml` is one of the syntax_test files because it has the `syntax_test` prefix. Just name it differently.

**Comment by jwortmann** [comment]
Thanks, now everything works!
