### ISSUE TITLE
GitHub actions times out

### ISSUE THREAD

**Issue by niosus** [SublimeText/UnitTesting#178]
I've been trying to transition my plugin to GitHub actions following your example, but my builds mostly fail with an error that I fail to understand, so I thought maybe you have encountered it before and would be able to point me in the correct direction. It is probably not because of UnitTesting package, but I need to start somewhere :)

Error:
```
Running command: run_tests --coverage
Unable to connect to dbus
Schedule:
  syntax_compatibility: None
  syntax_test: None
  package: EasyClangComplete
  color_scheme_test: None
  coverage: True
  output: /github/home/.config/sublime-text-3/Packages/User/UnitTesting/EasyClangComplete/result
Wait for tests output..................................
Timeout: Could not obtain tests output.
Maybe Sublime Text is not responding or the tests outputis being written to the wrong file.
##[error]Process completed with exit code 1.
```

Example run: https://github.com/niosus/EasyClangComplete/pull/681/checks?check_run_id=523900818

Any hints are much appreciated!

**Comment by niosus** [comment]
@randy3k sorry for a direct mention, but did you maybe experience something like this?

**Comment by randy3k** [comment]
Maybe trying to capture the console?

**Comment by randy3k** [comment]
Wait, I now that you have al ready captured it. I cannot think of a reason for now. It is mostly because your package was not loaded due to a bug.

**Comment by randy3k** [comment]
One thing that you could try is to download the docker image and run it locally. You could also install a VNC server to check things.

**Comment by niosus** [comment]
Right, makes sense. I will try this. Just thought maybe you have already seen something like this. The funny thing is that it doesn't seem to happen every time. Thanks anyway!

**Comment by niosus** [comment]
Also, seems that its not a dbus thing. [This build](https://github.com/niosus/EasyClangComplete/runs/582701443?check_suite_focus=true) (ignore the fact that it fails) can actually get proper output from the tests. :shrug:

**Comment by randy3k** [comment]
You could pretty much ignore the dubs error, I guess. I have seen it many times and it didn’t break anything for me.

**Comment by niosus** [comment]
Is there any way to tweak the timeout of the script?

**Comment by niosus** [comment]
I can see that it is defaulted here: https://github.com/SublimeText/UnitTesting/blob/9bec564cd965bc9f1a81cc9280ff10df91ddf55d/sbin/run_tests.py#L69

But I don't see a way to pass it through in any way. Is there a reason for a 10 second timeout here? I have a feeling, that on some containers it takes more time to start the test suite and therefore everything fails.

**Comment by niosus** [comment]
I am not sure. I don't really think it is related as it only happens when using GitHub actions and never on appveyor or Travis.

**Comment by niosus** [comment]
I haven't touched my code in a while there and just went back to it and it is not hanging anymore. So closing.
