### ISSUE TITLE
start_sublime_text helper

### ISSUE THREAD

**Issue by rchl** [SublimeText/UnitTesting#180]
There is this `start_sublime_text` that starts sublime:
https://github.com/SublimeText/UnitTesting/blob/ecf6add3e6416de9105bdae0fe323fa316b2865a/sbin/run_tests.py#L99

1) Why does it use `&`? I understand that this means "run command in the background" but is it really relevant here? It seems to work just fine.
2) On opening, a /tmp/ file is opened in a tab. Can this be avoided? I don't exactly see the point of it. I guess this is something related to `subprocess` but I don't exactly understand why it happens.
3) I think this could be improved by passing `--stay` argument as otherwise, once the tab this command opens is closed, focus switches back to the terminal which can (and does) affect some focus specific tests

**Comment by randy3k** [comment]
1. It was the original comment for the `&`. I don't know if it is still needed.
```
        # In some Linux/macOS CI environments, starting ST simply with `subl`
        # causes the CI process to time out. Using `subl &` seems to solve
        # this.
```
2. I remember that there was a problem of `subl` and I vaguely recall that it has been fixed in Sublime Text 4.
3. @rwols is actually working on a refactoring, perhaps you could give your 2 cents there: #179

**Comment by rchl** [comment]
2) That seems to happen only when using `&` in the command so removing it would solve both 1 and 2.
But then I suppose we can't do much if we don't know a specific reason why it's here.

**Comment by rchl** [comment]
@FichteFoll made a comment on Discord that makes it clear:
> note that ST3's subl used to stick around if it there was no existing sublime process running already. the behavior of always starting and communicating with a background process is new in ST4 afaict

And indeed it blocks if ST3 is not yet started

**Comment by rchl** [comment]
@rwols would you like to handle 3) on your branch or separately. I think `--stay` should actually help with LSP tests so it would be perfect if we could get that change separately ASAP.

**Comment by rwols** [comment]
Well, my PR is somewhat larger than that change.
I think it's best if it were a separate PR, my PR might take a while as I have to modify Windows, macOS and docker dependent files.

**Comment by randy3k** [comment]
#181 has closed it.
