### ISSUE TITLE
gtk/gdk issues on Linux

### ISSUE THREAD

**Issue by abathur** [SublimeText/UnitTesting#182]
I'm updating a plugin I haven't touched in a couple years and trying to get travis-ci working again, but I'm running into GDK/GTK-related failures on Linux. I went ahead and commented out other builds to focus on this failure first. Hopefully just doing/missing something obvious.

Build output https://travis-ci.org/github/abathur/constellation/jobs/680364869

Config: https://github.com/abathur/constellation/blob/4ee77ae3cab3345867a8fa9489a154a0327a64ee/.travis.yml

I've looked around for a bit for evidence anyone else is trying to mitigate these issues and haven't spotted anything. I'm not specifying a distribution, but it is still xenial, and I see other plugins with successful builds against it.

**Comment by randy3k** [comment]
what if you add `language: python`? 
https://github.com/SublimeText/UnitTesting/blob/master/.travis.yml#L7

It may use a different container that has the required libraries.

**Comment by abathur** [comment]
Erg! Thanks--looks like that does the trick. I didn't suspect that would matter since the osx tests were running, and I know it didn't use the python language setting directly.

**Comment by randy3k** [comment]
AFAIK, there is only one variation of container for macOS. Specifying `language` doesn't work for macOS.
