### ISSUE TITLE
Freeze when setting project data on window

### ISSUE THREAD

**Issue by rwols** [SublimeText/UnitTesting#183]
The following freezes Sublime Text 4074:

```python
class Foo(unittest.TestCase):

    def test_foo(self):
        w = sublime.active_window()
        w.set_project_data({'settings': {'a': 'b'}})
```

**Comment by rwols** [comment]
Looks like I can use `unittesting.mock.MagicMock` for my purposes.

```
w = sublime.active_window()
w.project_data = MagicMock(return_value={'settings': {'a': 'b'}})
```

**Comment by randy3k** [comment]
I cannot actually reproduce it. How did you run the test?

**Comment by rwols** [comment]
My setup was:

- Clone the LSP repo https://github.com/sublimelsp/LSP/
- Have a .sublime-project active that includes LSP as folder
- Open tests/test_configurations.py
- Paste the above test into the file
- Run "UnitTesting: Test Current File"

**Comment by rwols** [comment]
Cannot reproduce.
