### ISSUE TITLE
Provide a way to cancel the test runner

### ISSUE THREAD

**Issue by rwols** [SublimeText/UnitTesting#185]
We're getting at around 200 tests now for LSP and we have a ton of `yield lambda: condition()` in setUp and tearDown methods. It can take a long time to wait for UnitTesting to finish if every one of those setUp methods fail to await the condition.

**Comment by rwols** [comment]
I know that `"failfast"` exists for unittesting.json but it would be nice to keep that set at `False` and cancel the test runner via the command palette.

**Comment by deathaxe** [comment]
All settings available in `unittesting.json` can also be passed to the commands and take precedence.

Adding the following to _Default.sublime-commands_ would provide a test command, which always fails on first caught exception.

```json
  {
    "caption": "UnitTesting: Test Current Package (Fail Fast)",
    "command": "unit_testing_current_package",
    "args": {"failfast": true},
  },
```
