### ISSUE TITLE
Implement deferred versions of setUpClass and tearDownClass class methods

### ISSUE THREAD

**Issue by rwols** [SublimeText/UnitTesting#187]
I would like to move some time-consuming set up and teardown in my tests to the suite level:

- I have to create a new view and wait for it to be done loading
- I have to add a test configuration language server
- I have to wait for that test language server to start, initialize, wait for the initialized notification, and wait for the textDocument/didOpen notification

After a test is done, there is more boilerplate to wait for:

- I have to shutdown the language server and wait for it to be shut down
- I have to close the view
- Remove the test configuration

I would like this to happen at the testsuite level, not the individual test method level. For this I need the `setUpClass` and `tearDownClass` classmethods of `unittest.TestCase` to be able to be ran deferred as well.

https://docs.python.org/3/library/unittest.html#setupclass-and-teardownclass

**Comment by randy3k** [comment]
IIRC, `setUpClass` and `tearDownClass` could also be generators as well.

**Comment by rwols** [comment]
Thanks. [Used here now](https://github.com/sublimelsp/LSP/pull/1397).
