### ISSUE TITLE
UnitTesting CI for ST4

### ISSUE THREAD

**Issue by rwols** [SublimeText/UnitTesting#189]
Now that ST4 is public, I am wondering what the appropriate steps are to get an ST4 Github Action running.

**Comment by randy3k** [comment]
I am working on it at https://github.com/SublimeText/UnitTesting/tree/fourpointzero. Should be able to merge in a few days.

**Comment by randy3k** [comment]
The master branch should work with ST4. Use the environmental variable `UNITTESTING_TAG: master` in your scripts.

**Comment by randy3k** [comment]
By the way, `coverage` tests are still not working yet for python 3.8 plugins because of the package control dependencies.
