### ISSUE TITLE
Testing a dependency within CI

### ISSUE THREAD

**Issue by rchl** [SublimeText/UnitTesting#193]
I'm trying to set up testing for a dependency (see https://github.com/sublimelsp/lsp_utils/pull/70) within a Github Actions.

There are some problems with that.

By default the CI script bootstraps Package Control with `ignore_vcs_packages` set to `true`. Having that option enabled with a cloned dependency in Packages results in PC showing an error dialog:

![Screenshot 2021-06-19 at 21 43 57](https://user-images.githubusercontent.com/153197/122653910-39a69100-d148-11eb-973a-2baffe8c275e.png)

and UnitTesting script failing the `install_package_control` step with:

```
Skipping git package lsp_utils since the setting "ignore_vcs_packages" is set to true
missing dependencies:
lsp_utils
Timeout: Fail to install Package Control.
Error: Process completed with exit code 1.
```
source: https://github.com/sublimelsp/lsp_utils/runs/2865424911

With `ignore_vcs_packages` set to `false` it also errors out with:

```
Error executing: /usr/bin/git symbolic-ref -q HEAD
Working directory: /github/home/.config/sublime-text/Packages/lsp_utils
VCS-based packages can be ignored by changing the "ignore_vcs_packages" setting to true.
Sublime Text will need to be restarted once the setting is changed.
missing dependencies:
lsp_utils
Timeout: Fail to install Package Control.
Error: Process completed with exit code 1.
```
source: https://github.com/sublimelsp/lsp_utils/runs/2865746622

I'm looking for some ideas on how to handle this.

**Comment by rchl** [comment]
For context, when doing the same in a local, clean ST build, I'm getting the same message and what I need to do to get that dependency registered in the loader is I have to manually trigger `Package Control: Install Local Dependency` from the Command Palette and select `lsp_utils`.

So I'm trying to figure out if there is some solution to that without involving any changes in PC itself since that would take a very long time, even if accepted.

**Comment by rchl** [comment]
One, not that clean, solution that just came to my mind is:
 - run `github.sh install_package LSP-pyright master https://github.com/sublimelsp/LSP-pyright.git` to install a package that requires `lsp_utils`
 - run `github.sh install_package_control` to  let PC install the `lsp_utils` dependency
 - in the next CI step, manually delete the installed dependency and then add my local version

**Comment by randy3k** [comment]
One solution is to remove the `.git` subdirectory of the repo. I remember I have to do it for one particular instance.

**Comment by rchl** [comment]
If I do that then PC will overwrite the directory with the latest released version instead of the one I want to test.

**Comment by rchl** [comment]
The idea above seems to have worked (see https://github.com/sublimelsp/lsp_utils/pull/70/commits/759e9755d9ccd729108365fe7a20586ecb80d413).

Obviously it's very hacky though and I would want to avoid referencing the Packages path in the CI workflow and rely completely on the original script...

**Comment by randy3k** [comment]
I thing we could add a flag to the bootstrap command so that the current repo is not copied to ST https://github.com/SublimeText/UnitTesting/blob/master/sbin/ci.sh#L29
And extract this part as a separate function which could be then be called later to  replace the installed dependency.

**Comment by rchl** [comment]
Yeah, that should work. Was hoping we could find some alternative angle at this issue that I couldn't think of. :)
