### ISSUE TITLE
unittesting module named differently in 3.3/3.8

### ISSUE THREAD

**Issue by rchl** [SublimeText/UnitTesting#196]
Is it on purpose that for 3.3 runtime the module name uses CamelCase while for 3.8 it uses lowercase?

https://github.com/SublimeText/UnitTesting/blob/e8759d1754ac42efd8f87bc3ca169a9586c6369a/py33/ut.py#L7
https://github.com/SublimeText/UnitTesting/blob/e8759d1754ac42efd8f87bc3ca169a9586c6369a/ut.py#L25

It might not be causing issues for testing but it does for type-checking.

**Comment by randy3k** [comment]
They are different modules. `UnitTesting` is the top level module and there is `UnitTesting.unittesting`. An alias was added to point `unittesting` to `UnitTesting.unittesting`.

**Comment by rchl** [comment]
I guess my issue with types is then due to `unittesting` not being in the `sys.path`. Basically when I write `from unittesting import DeferrableTestCase` it's reported as import error by pyright. I probably can extend the path manually to make it work or something.
