### ISSUE TITLE
MacOS action hangs

### ISSUE THREAD

**Issue by niosus** [SublimeText/UnitTesting#202]
Hey @randy3k, thanks again for putting continuous efforts into making this package! 🙏 

I've just fully switched to using GitHub actions after some time off my package but it seems that the MacOS hangs while running the tests. Here is an example job: https://github.com/niosus/EasyClangComplete/runs/4421705935?check_suite_focus=true 

Would you have an idea what could be the case here? Did you maybe happen to see it happen in other projects? 

If not, I will try to reduce the scope of the tests that I run and try to narrow it down to smth meaningful.

**Comment by randy3k** [comment]
> Would you have an idea what could be the case here? Did you maybe happen to see it happen in other projects?
Unfortunately no...

You might try https://github.com/mxschmitt/action-tmate which make debugging a bit easier.
Have to sleep now, let me see if I could find something to look into it when I wake up. :)

**Comment by randy3k** [comment]
I've logged in to the runner with tmate and discovered that the test was frozen at `Test if no json is found.`.

PS: UnitTesting currently does not handle the case that any tests are frozen indefinitely. Perhaps we should add a timeout, say 5 minutes, for each test case.

**Comment by randy3k** [comment]
FYI, you could run the tests with the following two lines via `tmate`.

```
cd "$SUBLIME_TEXT_PACKAGES/EasyClangComplete"
python3 ../UnitTesting/scripts/run_tests.py EasyClangComplete
```

**Comment by randy3k** [comment]
I have pushed some update to the action scripts. If you re-run the tests, you should see [this](https://github.com/randy3k/EasyClangComplete/runs/4425849057?check_suite_focus=true):
```
Wait for tests output.........
Start to read output...
#####
async runner is deprecated, consider using the DeferrableTestCase.
#####

Darwin
test_singleton (tests.test_singleton.test_singleton)
Test if singleton returns a unique reference. ... ok
test_override_job (tests.test_thread_pool.TestThreadPool)
Test overriding job. ... ok
test_single_job (tests.test_thread_pool.TestThreadPool)
Test single job. ... ok
test_init (tests.test_row_col.TestRowCol)
Initialization test. ... ok
test_init_from_one_indexed (tests.test_row_col.TestRowCol)
Initialization test from 1-indexed row and column. ... ok
test_init_from_zero_indexed (tests.test_row_col.TestRowCol)
Initialization test from 0-indexed row and column. ... ok
test_location (tests.test_row_col.TestRowCol)
Location is valid. ... ok
test_setup_view (tests.test_row_col.TestRowCol)
Test that setup view correctly sets up the view. ... ok
test_get_catkin_ws (tests.test_catkinizer.TestCatkinizer)
Test getting a catkin workspace. ... ok
test_get_cmake_entry (tests.test_catkinizer.TestCatkinizer)
Get cmake entry. ... ok
test_get_ros_distro_path (tests.test_catkinizer.TestCatkinizer)
Check that we can get the paths to ros. ... /Users/runner/Library/Application Support/Sublime Text/Packages/EasyClangComplete/tests/cmake_tests
ok
test_init (tests.test_catkinizer.TestCatkinizer)
Test initialization. ... ok
test_setting_getting_project_data (tests.test_catkinizer.TestCatkinizer)
Test setting and getting project data. ... ok
test_builder (tests.test_flag.TestFlag)
Test tokenizing a list of all split flags. ... ok
test_builder_invalid (tests.test_flag.TestFlag)
Test tokenizing invalid flags. ... ok
test_hash (tests.test_flag.TestFlag)
Test that hash is always the same when needed. ... ok
test_init (tests.test_flag.TestFlag)
Initialization test. ... ok
test_put_into_container (tests.test_flag.TestFlag)
Test adding to hashed container. ... ok
test_tokenize (tests.test_flag.TestFlag)
Test tokenizing a list of all split flags. ... ok
test_empty_include_and_defines (tests.test_CppProperties.TestCppProperties)
Test that empty fields are handled correctly. ... ok
test_expand_environment_variables (tests.test_CppProperties.TestCppProperties)
Test environment variables are expanded. ... ok
test_get_all_flags (tests.test_CppProperties.TestCppProperties)
Test if CppProperties.json is found. ... ok
test_no_db_in_folder (tests.test_CppProperties.TestCppProperties)
Test if no json is found. ... 
Timeout: output is frozen.
```

**Comment by niosus** [comment]
Oh, man! Thanks for all the time you've put into this, I'll check it out from here on. :pray:

**Comment by niosus** [comment]
Ok, as always, the issue was found between the screen and the back of the chair. Somehow in Github actions on MacOS an error surfaced that I did not see before. The reason for the hand was that because of the way some non-existing paths were formed MacOS wanted to access network volumes for those. With GUI MacOS would prompt the user and in the CI it would just hang. Thanks a lot for bearing with me and for your help in figuring this out! 🙏
