### ISSUE TITLE
GH actions fail to download binaries

### ISSUE THREAD

**Issue by yeraydiazdiaz** [SublimeText/UnitTesting#204]
Hello and thanks for your work on UnitTesting, I'm finding it incredibly useful.

I was integrating the GitHub actions for my package and noticed all jobs for all platforms failed, here's an example https://github.com/yeraydiazdiaz/sublime-rest-client/runs/6644160368?check_suite_focus=true

I believe this is caused by Sublime changing the download URLs in https://www.sublimetext.com/download to something like https://www.sublimetext.com/download_thanks?target=mac, which the download script cannot parse and fails, but I might be wrong.

**Comment by randy3k** [comment]
Fixed in v1.5.8.

**Comment by yeraydiazdiaz** [comment]
Wow, great response time, thanks!
