### ISSUE TITLE
[MacOS, GithubActions]Timeout: Fail to install Package Control.

### ISSUE THREAD

**Issue by predragnikolic** [SublimeText/UnitTesting#267]
Github Actions on MacOS are broken:
https://github.com/sublimelsp/LSP/actions/runs/8830051521/job/24242362345?pr=2433
https://github.com/sublimelsp/LSP/actions/runs/8813398154/job/24465908824?pr=2440
https://github.com/sublimelsp/LSP/actions/runs/8830027149/job/24546621951?pr=2448

Other OSes work fine.

**Comment by deathaxe** [comment]
Duplicate of https://github.com/SublimeText/UnitTesting/issues/265

It appears the "coverage" library can't be resolved for python 3.3 on MacOS.

**Comment by predragnikolic** [comment]
Ok, I'll subscribe to #265
