### ISSUE TITLE
Add support for `yield self.assert*(...)`

### ISSUE THREAD

**Issue by giampaolo** [SublimeText/UnitTesting#273]
I'm not sure how feasible this is to implement, but here goes. When writing unit tests for ST it's very common to wait for a condition to happen. E.g.:

```python
    def test_something(self):
        self.window.run_command("show_panel", {"panel": "console"})
        yield lambda: self.window.active_panel() == "console"
```

Despite this works, it does not give any hint on what `active_panel()` returns if the condition fails due to a timeout.  It would therefore be nice to do this instead:

```python
    def test_something(self):
        self.window.run_command("show_panel", {"panel": "console"})
        yield lambda: self.assertEqual(self.window.active_panel(), "console")
```

**Comment by deathaxe** [comment]
Interesting idea. When assuming assertions to always return `None` and normal conditions only `True` or `False`, it should be doable with hopefully low risk on breaking anyones test cases.
