### ISSUE TITLE
What does the verbosity setting value means?

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/UnitTesting#68]
I could not find a documentation for it. Is there some?

I experienced a little with it:

1. Putting it to 2, it displays each executed tests name + ok.
1. Putting it to 1, displays like the default Python unit test runner.
1. Putting it to 0, seems to only displays the overall progress.

**Comment by randy3k** [comment]
Python docs also doesn't say much https://docs.python.org/3/library/unittest.html#unittest.TextTestRunner

**Comment by evandrocoan** [comment]
Fixed by:

1. [What numbers can you pass as verbosity in running Python Unit Test Suites?](https://stackoverflow.com/questions/1322575/what-numbers-can-you-pass-as-verbosity-in-running-python-unit-test-suites)
