### ISSUE TITLE
Travis OSX build is halting

### ISSUE THREAD

**Issue by evandrocoan** [SublimeText/UnitTesting#78]
The Linux build is going OK, but the OSX is always halting with this:
```
Wait for Sublime Text response
......
Start to read output...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
1 .https://travis-ci.org/evandrocoan/PackagesManager/jobs/325856633

The package PackagesManager is just Package Control renamed without space on the name, but setup to run the unit tests with UnitTesting.

I just have setup another package https://travis-ci.org/evandrocoan/WrapPlus and the OSX is building just fine. Perhaps issue with PackagesManager this is related with:

1. https://github.com/SublimeText/UnitTesting/issues/57 Failures on OSX

**Comment by randy3k** [comment]
It does not seem to be an issue of UnitTesting, I have not idea why the tests do not run on macOS. Did you try running it locally?

**Comment by randy3k** [comment]
Also, it is not related to #57. Your output suggests that the tests have started executing but somehow became frozen later.

**Comment by evandrocoan** [comment]
Thanks! Indeed, I set the verbosity level to 2, and after running the tests, its showed that it ran until the penultimate test, while comparing the output results with the Travis build:
```
test_get_packages_20_github (all_tests.providers_tests.RepositoryProviderTests) ... ERROR
test_get_packages_300_explicit (all_tests.providers_tests.RepositoryProviderTests) ... ok
test_get_packages_300_bitbucket (all_tests.providers_tests.RepositoryProviderTests) ... ok

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated

test_get_packages_300_explicit (all_tests.providers_tests.RepositoryProviderTests) ... ok

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```
1. https://travis-ci.org/evandrocoan/PackagesManager/jobs/325878766
1. https://ci.appveyor.com/project/evandrocoan/packagesmanager/build/1.0.14

It seems that something is not working quite right on OSX installations.

**Comment by evandrocoan** [comment]
> Did you try running it locally?

I do not have any OSX locally to test it for now 😢
