### ISSUE TITLE
Can't find this package on Package Control - Missing error: Package info was unavailable ...

### ISSUE THREAD

**Issue by pichillilorenzo** [SublimeText/UnitTesting#84]
I was trying to find the package with Package Control on Sublime Text 3 (build 3143) but this package doesn't appear at all in the list! 

I think that the problem is caused because of this:
![schermata 2018-02-25 alle 00 39 49](https://user-images.githubusercontent.com/5956938/36636314-9c3cf79e-19c4-11e8-9952-27494ba5a481.png)

**Comment by ehuss** [comment]
It's being worked on.  See wbond/package_control#1334
