### ISSUE TITLE
Subclass of TestCase that provides a view object.

### ISSUE THREAD

**Issue by Thom1729** [SublimeText/UnitTesting#89]
A common pattern in Sublime package unit tests is to create a view, perform operations on that view, assert that the contents of the view are equal to some value, and tear down the view afterward. It would be convenient to have a subclass of TestCase that does this for you.

Example implementation:

```python
import sublime

from unittest import TestCase

class ViewTestCase(TestCase):
    def setUp(self):
        self.view = sublime.active_window().new_file()

    def tearDown(self):
        if self.view:
            self.view.set_scratch(True)
            self.view.window().focus_view(self.view)
            self.view.window().run_command("close_file")

    def assertViewContentsEqual(self, text):
        self.assertEqual(
            self.view.substr(sublime.Region(0, self.view.size())),
            text
        )
```

Example usage:

```python
import sublime

from UnitTesting import ViewTestCase

class TestJsxCloseTag(ViewTestCase):
    def setUp(self):
        super().setUp()
        self.view.set_syntax_file('Packages/User/JS Custom/Tests/jsx/jsx.sublime-syntax')

    def test_close_tag(self):
        self.view.run_command('insert', { 'characters': '<foo>' })
        self.view.run_command('jsx_close_tag')
        self.assertViewContentsEqual('<foo></foo>')
```

Other thoughts:

- Will this work nicely with Deferrable test cases?
- Is there a better way of closing a view than the one above?
- Should there be a mechanism for specifying default settings?
- Are there other common base cases we could provide?
- Where should something like this go in the source? I'm not very familiar with this package's internals.

**Comment by randy3k** [comment]
There are some helper functions [here](https://github.com/SublimeText/UnitTesting/blob/master/unittesting/helpers.py). It should work with `DeferrableTestCase`, however, you would need to use `yield from super().setUp()` instead.
See https://github.com/divmain/GitSavvy/blob/master/tests/test_git/common.py as an example.

**Comment by Thom1729** [comment]
Neat; I missed the helpers subpackage. Would the following make sense?

- Create a `helpers` directory.
- Move `helpers.py` to `helpers/temp_directory_test_case.py`.
- Add `helpers/view_test_case.py`.
- Reference the above in `helpers/__init__.py`.

**Comment by randy3k** [comment]
Sure.
